import localFont from "next/font/local";
import "./globals.css";
import RTKProvider from "@/state/ReduxProvider";
import { UserProvider } from '@auth0/nextjs-auth0/client';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RTKProvider>
          <UserProvider>
        {children}
        </UserProvider>
        </RTKProvider>
      </body>
    </html>
  );
}
