import localFont from "next/font/local";
import "./globals.css";
import RTKProvider from "@/state/ReduxProvider";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import ReactQueryClientProvider from "@/components/Providers/ReactQueryProvider";
import { MantineProvider } from "@mantine/core";
import '@mantine/core/styles.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Revive Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <MantineProvider
            withGlobalStyles
            withNormalizeCSS
            theme={{
              components: {
                Pagination: {
                  styles: {
                    item: {
                      backgroundColor: '#1c7ed6',
                      color: 'white',
                      '&:hover': {
                        backgroundColor: '#1b6ec2',
                      },
                    },
                    active: {
                      backgroundColor: '#1b6ec2',
                      color: 'white',
                      fontWeight: 'bold',
                    },
                  },
                },
              },
            }}
          >
            <RTKProvider>
              <UserProvider>
                <div className='w-full overflow-auto'>
                  {children}
                </div>
              </UserProvider>
            </RTKProvider>
          </MantineProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
