import {
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
} from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import {
    Card,
    CardAction,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import NewMemberRevenew from "./revenewcomponents/NewAdmissionRevenew"
import MembershipRenewal from "./revenewcomponents/MembershipRenewal"
import LockerRevenew from "./revenewcomponents/LockerRevenew"
import TotalRevenew from "./revenewcomponents/TotalRevenew"

const RevenewDashboard = () => {
    return (
        <div className="w-full">

            <Tabs defaultValue="newadmissionrenewal">
                <TabsList className='w-full grid grid-cols-1 lg:grid-cols-4 gap-4'>
                    <TabsTrigger value="newadmissionrenewal">
                        <Card>
                            <div>
                                <h1>New Admission Revenew</h1>
                                <h1>NPR 500000</h1>
                                <p>Revenew generated by new members</p>
                            </div>
                        </Card>
                    </TabsTrigger>

                    <TabsTrigger value="membershiprenewal">
                        <Card>
                            <div>
                                <h1>Membership Renewal</h1>
                                <h1>NPR 500000</h1>
                                <p>Revenew generated by membership renewel</p>
                            </div>
                        </Card>
                    </TabsTrigger>

                    <TabsTrigger value="lockerrenewal">
                        <Card>
                            <div>
                                <h1>Lockers Renewal</h1>
                                <h1>NPR 500000</h1>
                                <p>Revenew generated by lockers</p>
                            </div>
                        </Card>
                    </TabsTrigger>

                    <TabsTrigger value="totalrevenew">
                        <Card>
                            <div>
                                <h1>Total Revenew</h1>
                                <h1>NPR 500000</h1>
                                <p>Total Revenew generated</p>
                            </div>
                        </Card>
                    </TabsTrigger>
                </TabsList>

                <TabsContent value="newadmissionrenewal">
                    <NewMemberRevenew />
                </TabsContent>
                <TabsContent value="membershiprenewal">
                    <MembershipRenewal />
                </TabsContent>
                <TabsContent value="lockerrenewal">
                    <LockerRevenew />
                </TabsContent>
                <TabsContent value="totalrevenew">
                    <TotalRevenew />
                </TabsContent>
            </Tabs>
        </div >
    )
}
export default RevenewDashboard;