import Header from "./Header";
import Sidebar from "./Sidebar";

export const metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
    return (
        <div className='min-h-screen flex'>
            <div className="md:w-[14%] bg-red-400 hidden md:flex">
                <Sidebar />
            </div>
            <div className="md:w-[86%]">
                <div className="w-full">
                    <Header />
                </div>
                <div className="w-full h-screen bg-blue-400">{children}</div>
            </div>
        </div>
    );
}
