import Header from "./Header";
import Sidebar from "./Sidebar";

export const metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
    return (
        <div className='min-h-screen flex'>
            <div className="w-[2%] md:w-[14%] bg-red-400"><Sidebar /></div>
            <div className="w-[98%] md:w-[84%]">
                <div className="w-full py-8"><Header /></div>
                <div className="w-full h-screen bg-blue-400">{children}</div>
            </div>
        </div>
    );
}
