'use client';

const AdminDashboard = () => {


  return (
    <div>
      <h1>Admin Dashboard In Next JS</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, obcaecati ducimus a, corrupti repudiandae consectetur voluptate dolor magni officia in deleniti error vero, necessitatibus at. Sunt pariatur repellendus nesciunt voluptates!</p>
    </div>
  )
}

export default AdminDashboard
